apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  labels:
    name: pvc1
spec:
  storageClassName: mystorageclass # phải chọn ra class mà nó tìm ra những pv trên cluster và nó sẽ gắn kết vào nhưng pv đó ==> Yêu câu truy cập PV có stronageClassNmae là mystringaeclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Mi
