apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deployapp
spec:
  maxReplicas: 5
  minReplicas: 3
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployapp
status:
  currentReplicas: 2
  desiredReplicas: 2
