apiVersion: v1
kind: Pod
metadata:
  name: nginx-swarmtest
  labels:
    app: myapp
spec:
  containers:
    - name: n1
      image: nginx:1.17.6
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"
      ports:
        - containerPort: 80
    - name: s1
      image: busybox
      command: ["sh", "-c", "while true; do echo hello; sleep 10; done"]
      resources:
        limits:
          memory: "150Mi"
          cpu: "100m"
      ports:
        - containerPort: 8085
