apiVersion: v1
kind: Pod
metadata:
  name: tools
  labels:
    app: tools
spec:
  containers:
    - name: node
      image: busybox
      command: ["sh", "-c", "while true; do echo hello; sleep 10; done"]
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"
